Bugfix/2006 wsdl performance
qorelanguage/module-xml pull request #109
Opened 2017-08-04 11:36 UTC by davidnich

2017-08-04 11:55 UTC, davidnich commented
requires https://github.com/qorelanguage/qore/pull/2035 before jenkins will pass

2017-08-08 16:16 UTC, omusil24 requested changes

2017-08-08 16:16 UTC, omusil24 commented on qlib/WSDL.qm
> +    XsdAbstractType rv := tmap{name};
Shouldn't there be "or_nothing" type here?

2017-08-08 16:18 UTC, davidnich commented on qlib/WSDL.qm
> +    XsdAbstractType rv := tmap{name};
right, done

2017-08-08 16:19 UTC, omusil24 approved these changes

2017-08-08 16:20 UTC, merged